In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import seaborn as sns

In [178]:
# import the villagers' wiki

the reason I chose the datasets I will be using is to find out what the villagers like, the gifts that everyone likes and which items a person should farm to use as gifts

In [3]:
# First step is to import the url for the website
stardew_villagers_url = 'https://stardewvalleywiki.com/Villagers'

In [4]:
# Second step I need to set a variable for requesting the HTML of the website.
stardew_villagers_html = requests.get(stardew_villagers_url).content

#Third step setting the variable for the HTML output using beautiful soup
stardew_villagers = BeautifulSoup(stardew_villagers_html,'html.parser')

In [180]:
# At first I struggled to find exactly which part of the HTML all the villager's names were on, however, once I found it I used it to find all villager names.
#this will be used later to merge with other tables.
stardew_people = stardew_villagers.find_all('div', 'gallerytext')

In [6]:
stardew_people

[<div class="gallerytext">
 <p><a href="/Alex" title="Alex">Alex</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Elliott" title="Elliott">Elliott</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Harvey" title="Harvey">Harvey</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Sam" title="Sam">Sam</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Sebastian" title="Sebastian">Sebastian</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Shane" title="Shane">Shane</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Abigail" title="Abigail">Abigail</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Emily" title="Emily">Emily</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Haley" title="Haley">Haley</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Leah" title="Leah">Leah</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Maru" title="Maru">Maru</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Penny" title="Penny">Penny</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Caroline" title="Caroline">Caroline</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Clint" title="Clint">Clint</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Demetrius" title="Demetrius">Demetrius</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Dwarf" title="Dwarf">Dwarf</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Evelyn" title="Evelyn">Evelyn</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/George" title="George">George</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Gus" title="Gus">Gus</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Jas" title="Jas">Jas</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Jodi" title="Jodi">Jodi</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Kent" title="Kent">Kent</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Krobus" title="Krobus">Krobus</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Leo" title="Leo">Leo</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Lewis" title="Lewis">Lewis</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Linus" title="Linus">Linus</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Marnie" title="Marnie">Marnie</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Pam" title="Pam">Pam</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Pierre" title="Pierre">Pierre</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Robin" title="Robin">Robin</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Sandy" title="Sandy">Sandy</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Vincent" title="Vincent">Vincent</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Willy" title="Willy">Willy</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Wizard" title="Wizard">Wizard</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Birdie" title="Birdie">Birdie</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Bouncer" title="Bouncer">Bouncer</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Fizz" title="Fizz">Fizz</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Gil" title="Gil">Gil</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Governor" title="Governor">Governor</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Grandpa" title="Grandpa">Grandpa</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Gunther" title="Gunther">Gunther</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Henchman" title="Henchman">Henchman</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Marlon" title="Marlon">Marlon</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Morris" title="Morris">Morris</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Mr._Qi" title="Mr. Qi">Mr. Qi</a>
 </p>
 </div>,
 <div class="gallerytext">
 <p><a href="/Professor_Snail" title="Professor Snail">Professor Snail</a>
 </p>
 </div>]

In [152]:
#create a list of only the villager's names from the website.
character_names = [person.text.strip() for person in stardew_people]

stardew_names_df = pd.DataFrame(character_names, columns=['Character'])
stardew_names_df.head()

   Character
0       Alex
1    Elliott
2     Harvey
3        Sam
4  Sebastian

In [14]:
# import character gift list
stardew_char_gifts_df = pd.read_csv('stardew_char_gifts.csv')

In [16]:
# show the head of the set to remove unnecessary columns and rename the columns that are useful
stardew_char_gifts_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Gift Loves and Likes,1.07,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,Birthday,Loves,Likes,NaN,Universal Like Gifts,Note
1,NaN,Kent,Spring 4,"Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'...","Universal Like (except Quartz, Sashimi, Tortil...",NaN,All gems besides Prismatic Shard which is cons...,"All Forage does not lnclude Red Mushroom, Cave..."
2,NaN,Lewis,Spring 7,"Vegetable Medley, Autumn's Bounty, Glazed Yams...","Universal Like (except Quartz), Parsnip, Cocon...",NaN,All Flowers,All Minerals
3,NaN,Vincent,Spring 10,"Cranberry Candy, Pink Cake, Grape, Rabbit's Fo...","Universal Likes (except All Vegetables, All Ar...",NaN,"Sweat Pea, Crocus, Sunflower, Tulip, Summer Sp...","Alamite, Bixite, Baryte, Aerinite, Calcite, Do..."
4,NaN,Haley,Spring 14,"Pink Cake, Fruit Salad, Coconut, Sunflower, Ra...","Universal Likes (except All Vegetables, Quartz...",NaN,All Vegetables,NaN

In [18]:
# use the .drop method to remove the columns from the sheet that do not store any information
stardew_char_clean = stardew_char_gifts_df.drop(['Unnamed: 0', 'Unnamed: 6', 'Unnamed: 5'], axis=1)
stardew_char_clean.head()

,Unnamed: 1,Unnamed: 2,Gift Loves and Likes,1.07,Unnamed: 7
0,NaN,Birthday,Loves,Likes,Note
1,Kent,Spring 4,"Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'...","Universal Like (except Quartz, Sashimi, Tortil...","All Forage does not lnclude Red Mushroom, Cave..."
2,Lewis,Spring 7,"Vegetable Medley, Autumn's Bounty, Glazed Yams...","Universal Like (except Quartz), Parsnip, Cocon...",All Minerals
3,Vincent,Spring 10,"Cranberry Candy, Pink Cake, Grape, Rabbit's Fo...","Universal Likes (except All Vegetables, All Ar...","Alamite, Bixite, Baryte, Aerinite, Calcite, Do..."
4,Haley,Spring 14,"Pink Cake, Fruit Salad, Coconut, Sunflower, Ra...","Universal Likes (except All Vegetables, Quartz...",NaN

In [147]:
# rename columns that are titled "Unnamed" or the "1.07" column and replace with a name that shows what the info is showing
stardew_char_rename = stardew_char_clean.rename(columns={'Unnamed: 1': 'Character', 'Unnamed 2': 'Character Birthday', '1.07': 'Universal Likes', 'Unnamed: 7': 'Extras' })

In [22]:
# remove the first row as it shows the names of the columns that were replaced.
stardew_char_likes_remove = stardew_char_rename.drop(stardew_char_rename.head(1).index)

# use .dropna to remove any unknown data in the set
stardew_char_likes = stardew_char_likes_remove.dropna(axis=1)

In [166]:
stardew_char_likes
# Unnamed: 2 isn't changing names (fix for final dataset)

,Character,Unnamed: 2,Gift Loves and Likes,Universal Likes
1,Kent,Spring 4,"Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'...","Universal Like (except Quartz, Sashimi, Tortil..."
2,Lewis,Spring 7,"Vegetable Medley, Autumn's Bounty, Glazed Yams...","Universal Like (except Quartz), Parsnip, Cocon..."
3,Vincent,Spring 10,"Cranberry Candy, Pink Cake, Grape, Rabbit's Fo...","Universal Likes (except All Vegetables, All Ar..."
4,Haley,Spring 14,"Pink Cake, Fruit Salad, Coconut, Sunflower, Ra...","Universal Likes (except All Vegetables, Quartz..."
5,Pam,Spring 18,"Parsnip Soup, Beer, Glazed Yams, Pale Ale Par...","Universal Likes (except Quartz), All Milk, All..."
6,Shane,Spring 20,"Beer, Hot Pepper, Pepper Poppers, Pizza, Rabbi...","Universal Likes (except Quartz, Pickles), All ..."
7,Pierre,Spring 26,"Fried Calamari, Rabbit's Foot, Prismatic Shard.","Universal Likes (except All Gems, Tortilla, Pa..."
8,Emily,Spring 27,"Survival Burger, Emerald, Aquamarine, Ruby, Am...","Universal Likes (except Rice Pudding, Ice Crea..."
9,Jas,Summer 4,"Fairy Rose, Pink Cake, Plum Pudding, Rabbit's ...","Universal Likes (except All Vegetables, All Ar..."
10,Gus,Summer 8,"Diamond, Escargot, Fish Taco, Orange, Rabbit's...","Universal Likes (except Quartz, Coleslaw), Daf..."
11,Maru,Summer 10,"Cheese Cauliflower, Cauliflower, Pepper Popper...","Universal Likes (except Honey, Maple Syrup, Pi..."
12,Alex,Summer 13,"Complete Breakfast, Salmon Dinner, Rabbit's Fo...","Universal Likes (except Quartz), All Eggs (exc..."
13,Sam,Summer 17,"Pizza, Cactus Fruit, Maple Bar, Tigerseye, Rab...","Universal Likes (except All Vegetables, Quartz..."
14,Demetrius,Summer 19,"Bean Hotpot, Ice Cream, Rice Pudding, Strawber...","Universal Likes (except Quartz), All Eggs (exc..."
15,Dwarf,Summer 22,"Amethyst, Aquamarine, Emerald, Jade, Omni Geod...","Universal Likes, Dwarf Scroll I, Dwarf Scroll ..."
16,Willy,Summer 24,"Catfish, Diamond, Iridium Bar, Octopus, Pumpki...","Universal Likes (except All Cooking), Tiger Tr..."
17,Penny,Fall 2,"Poppyseed Muffin, Red Plate, Tom Kha Soup, Roo...","Universal Likes (except Quartz, Beer, Wine, Pa..."
18,Elliot,Fall 5,"Pomegranate, Crab Cakes, Tom Kha Soup, Duck Fe...","Universal Likes (except Quartz, Pizza) , All F..."
19,Jodi,Fall 11,"Chocolate Cake, Crispy Bass, Diamond, Vegetabl...","Universal Likes (except Quartz, Garlic), All E..."
20,Abigail,Fall 13,"Blackberry Cobbler, Chocolate Cake, Spicy Eel,...",Universal Likes (except All Vegetables)
21,Sandy,Fall 15,"Crocus, Daffodil, Sweet Pea, Rabbit's Foot, Pr...","Universal Likes, All Fruits, All Vegetables, C..."
22,Marnie,Fall 18,"Diamond, Farmer's Lunch, Pink Cake, Pumpkin Pi...","Universal Likes, All Eggs (except Void egg), A..."
23,Robin,Fall 21,"Goat Cheese, Peach, Spaghetti, Rabbit's Foot, ...","Universal Likes, All Milk, All Fruits, Cheese,..."
24,George,Fall 24,"Fried Mushroom, Leek, Rabbit's Foot, Prismatic...","Universal Likes (except Quartz, All Flowers), ..."
25,Krobus,Winter 1,"Diamond, Iridium Bar, Pumpkin, Void Egg, Wild ...","Universal Likes (except All Cooking), Gold Bar."
26,Linus,Winter 3,"Blueberry Tart, Cactus Fruit, Coconut, Dish O'...","Universal Likes (except All Gems), All Eggs (e..."
27,Caroline,Winter 7,"Fish Taco, Summer Spangle, Rabbit's Foot, Pris...","Universal Likes (except Quartz, Mayonnaise, Du..."
28,Sebastian,Winter 10,"Frozen Tear, Pumpkin Soup, Sashimi, Void Egg, ...","Universal Likes (except All Flowers, Fried Egg..."
29,Harvey,Winter 14,"Super Meal, Lobster Bisque, Truffle Oil, Wine,...","Universal Likes (except Cheese, Goat Cheese, I..."
30,Wizard,Winter 17,"Super Cucumber, Purple Mushroom, Solar Essence...","Universal Likes, All Minerals."
31,Evelyn,Winter 20,"Beet, Chocolate Cake, Diamond, Fairy Rose, Stu...","Universal Likes (except Quartz, Fried Eel, Spi..."
32,Leah,Winter 23,"Salad, Vegetable Medley, Poppyseed Muffin, Sti...","Universal Likes (except Pizza, Pink Cake, Cook..."
33,Clint,Winter 26,"Emerald, Aquamarine, Ruby, Amethyst, Topaz, Ja...","Universal Likes (except Quartz, All Flowers), ..."

In [182]:
# this step I grouped the gift and universal likes columns to find every item each villager likes
stardew_char_likes['All Gifts'] = stardew_char_likes.apply(lambda d: d['Gift Loves and Likes'] + d['Universal Likes'], axis=1).sum()

In [28]:
stardew_char_likes

,Character,Unnamed: 2,Gift Loves and Likes,Universal Likes,All Gifts
1,Kent,Spring 4,"Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'...","Universal Like (except Quartz, Sashimi, Tortil...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
2,Lewis,Spring 7,"Vegetable Medley, Autumn's Bounty, Glazed Yams...","Universal Like (except Quartz), Parsnip, Cocon...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
3,Vincent,Spring 10,"Cranberry Candy, Pink Cake, Grape, Rabbit's Fo...","Universal Likes (except All Vegetables, All Ar...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
4,Haley,Spring 14,"Pink Cake, Fruit Salad, Coconut, Sunflower, Ra...","Universal Likes (except All Vegetables, Quartz...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
5,Pam,Spring 18,"Parsnip Soup, Beer, Glazed Yams, Pale Ale Par...","Universal Likes (except Quartz), All Milk, All...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
6,Shane,Spring 20,"Beer, Hot Pepper, Pepper Poppers, Pizza, Rabbi...","Universal Likes (except Quartz, Pickles), All ...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
7,Pierre,Spring 26,"Fried Calamari, Rabbit's Foot, Prismatic Shard.","Universal Likes (except All Gems, Tortilla, Pa...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
8,Emily,Spring 27,"Survival Burger, Emerald, Aquamarine, Ruby, Am...","Universal Likes (except Rice Pudding, Ice Crea...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
9,Jas,Summer 4,"Fairy Rose, Pink Cake, Plum Pudding, Rabbit's ...","Universal Likes (except All Vegetables, All Ar...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
10,Gus,Summer 8,"Diamond, Escargot, Fish Taco, Orange, Rabbit's...","Universal Likes (except Quartz, Coleslaw), Daf...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
11,Maru,Summer 10,"Cheese Cauliflower, Cauliflower, Pepper Popper...","Universal Likes (except Honey, Maple Syrup, Pi...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
12,Alex,Summer 13,"Complete Breakfast, Salmon Dinner, Rabbit's Fo...","Universal Likes (except Quartz), All Eggs (exc...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
13,Sam,Summer 17,"Pizza, Cactus Fruit, Maple Bar, Tigerseye, Rab...","Universal Likes (except All Vegetables, Quartz...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
14,Demetrius,Summer 19,"Bean Hotpot, Ice Cream, Rice Pudding, Strawber...","Universal Likes (except Quartz), All Eggs (exc...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
15,Dwarf,Summer 22,"Amethyst, Aquamarine, Emerald, Jade, Omni Geod...","Universal Likes, Dwarf Scroll I, Dwarf Scroll ...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
16,Willy,Summer 24,"Catfish, Diamond, Iridium Bar, Octopus, Pumpki...","Universal Likes (except All Cooking), Tiger Tr...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
17,Penny,Fall 2,"Poppyseed Muffin, Red Plate, Tom Kha Soup, Roo...","Universal Likes (except Quartz, Beer, Wine, Pa...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
18,Elliot,Fall 5,"Pomegranate, Crab Cakes, Tom Kha Soup, Duck Fe...","Universal Likes (except Quartz, Pizza) , All F...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
19,Jodi,Fall 11,"Chocolate Cake, Crispy Bass, Diamond, Vegetabl...","Universal Likes (except Quartz, Garlic), All E...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
20,Abigail,Fall 13,"Blackberry Cobbler, Chocolate Cake, Spicy Eel,...",Universal Likes (except All Vegetables),"Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
21,Sandy,Fall 15,"Crocus, Daffodil, Sweet Pea, Rabbit's Foot, Pr...","Universal Likes, All Fruits, All Vegetables, C...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
22,Marnie,Fall 18,"Diamond, Farmer's Lunch, Pink Cake, Pumpkin Pi...","Universal Likes, All Eggs (except Void egg), A...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
23,Robin,Fall 21,"Goat Cheese, Peach, Spaghetti, Rabbit's Foot, ...","Universal Likes, All Milk, All Fruits, Cheese,...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
24,George,Fall 24,"Fried Mushroom, Leek, Rabbit's Foot, Prismatic...","Universal Likes (except Quartz, All Flowers), ...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
25,Krobus,Winter 1,"Diamond, Iridium Bar, Pumpkin, Void Egg, Wild ...","Universal Likes (except All Cooking), Gold Bar.","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
26,Linus,Winter 3,"Blueberry Tart, Cactus Fruit, Coconut, Dish O'...","Universal Likes (except All Gems), All Eggs (e...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
27,Caroline,Winter 7,"Fish Taco, Summer Spangle, Rabbit's Foot, Pris...","Universal Likes (except Quartz, Mayonnaise, Du...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
28,Sebastian,Winter 10,"Frozen Tear, Pumpkin Soup, Sashimi, Void Egg, ...","Universal Likes (except All Flowers, Fried Egg...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
29,Harvey,Winter 14,"Super Meal, Lobster Bisque, Truffle Oil, Wine,...","Universal Likes (except Cheese, Goat Cheese, I...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
30,Wizard,Winter 17,"Super Cucumber, Purple Mushroom, Solar Essence...","Universal Likes, All Minerals.","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
31,Evelyn,Winter 20,"Beet, Chocolate Cake, Diamond, Fairy Rose, Stu...","Universal Likes (except Quartz, Fried Eel, Spi...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
32,Leah,Winter 23,"Salad, Vegetable Medley, Poppyseed Muffin, Sti...","Universal Likes (except Pizza, Pink Cake, Cook...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."
33,Clint,Winter 26,"Emerald, Aquamarine, Ruby, Amethyst, Topaz, Ja...","Universal Likes (except Quartz, All Flowers), ...","Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'..."

The dataset above was cleaned by removing data that was missing, as well as clearing out
the first row that was a repeat of the head of the dataset. Another step I took was renaming the heads of the
set because most of them were titled "Unnamed" from an error within the Google sheet. I also used the groupby
function to create a column titled "All Gifts" for every gift that each villager likes.

In [107]:
# import stardew items url
stardew_items_url = 'https://raw.githubusercontent.com/Cecax27/DS-Stardew-Valley-Crops-Profit/refs/heads/main/data/crops_preprocessed_data.csv'
stardew_items_df = pd.read_csv(stardew_items_url)

In [58]:
stardew_items_df.head()

,name,artisan_sell_price,base,description,egg_festival_price,energy,general_store_price,growth_time,jojamart_price,night_market_price,...,sell_price_regular,sell_price_silver,source,traveling_cart_price_max,traveling_cart_price_min,xp,spring,summer,fall,winter
0,Amaranth,NaN,Artisan (+40%),A purple grain cultivated by an ancient civili...,NaN,NaN,70.0,7,87.0,NaN,...,150.0,187.0,NaN,1000.0,105.0,21 Farming XP,False,False,True,False
1,Ancient Fruit,NaN,Artisan (+40%),It's been dormant for eons.,NaN,Inedible,NaN,28,NaN,NaN,...,550.0,687.0,NaN,1000.0,100.0,38 Farming XP,True,True,True,False
2,Artichoke,NaN,Artisan (+40%),The bud of a thistle plant. The spiny outer le...,NaN,NaN,30.0,8,NaN,NaN,...,160.0,200.0,NaN,1000.0,100.0,22 Farming XP,False,False,True,False
3,Beet,NaN,Artisan (+40%),"A sweet and earthy root vegatable. As a bonus,...",NaN,NaN,NaN,6,NaN,NaN,...,100.0,125.0,NaN,1000.0,100.0,16 Farming XP,False,False,True,False
4,Blue Jazz,NaN,Artisan (+40%),The flower grows in a sphere to invite as many...,NaN,NaN,30.0,7,37.0,30.0,...,50.0,62.0,NaN,1000.0,100.0,10 Farming XP,True,False,False,False

In [105]:
# this set has a lot of empty data so instead of removing columns or replacing the data
# i removed all the NaN items using .dropna
stardew_items_dropna = stardew_items_df.dropna(axis=1)
stardew_items_dropna.head()

,name,description,growth_time,regrowth_time
0,Amaranth,A purple grain cultivated by an ancient civili...,7,0
1,Ancient Fruit,It's been dormant for eons.,28,7
2,Artichoke,The bud of a thistle plant. The spiny outer le...,8,0
3,Beet,"A sweet and earthy root vegatable. As a bonus,...",6,0
4,Blue Jazz,The flower grows in a sphere to invite as many...,7,0

In [103]:
# take name and growth time columns from the stardew_items_dropna set for merging
stardew_items_cols = stardew_items_dropna[['name', 'growth_time']]

In [101]:
# use pd.concat to merge both datasets and prepare for data cleaning
merged_stardew = pd.concat([stardew_items_cols, stardew_char_likes])
merged_stardew

,name,growth_time,Character,Unnamed: 2,Gift Loves and Likes,Universal Likes
0,Amaranth,7.0,NaN,NaN,NaN,NaN
1,Ancient Fruit,28.0,NaN,NaN,NaN,NaN
2,Artichoke,8.0,NaN,NaN,NaN,NaN
3,Beet,6.0,NaN,NaN,NaN,NaN
4,Blue Jazz,7.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
29,NaN,NaN,Harvey,Winter 14,"Super Meal, Lobster Bisque, Truffle Oil, Wine,...","Universal Likes (except Cheese, Goat Cheese, I..."
30,NaN,NaN,Wizard,Winter 17,"Super Cucumber, Purple Mushroom, Solar Essence...","Universal Likes, All Minerals."
31,NaN,NaN,Evelyn,Winter 20,"Beet, Chocolate Cake, Diamond, Fairy Rose, Stu...","Universal Likes (except Quartz, Fried Eel, Spi..."
32,NaN,NaN,Leah,Winter 23,"Salad, Vegetable Medley, Poppyseed Muffin, Sti...","Universal Likes (except Pizza, Pink Cake, Cook..."
33,NaN,NaN,Clint,Winter 26,"Emerald, Aquamarine, Ruby, Amethyst, Topaz, Ja...","Universal Likes (except Quartz, All Flowers), ..."

In [168]:
# use .fillna to change NaN to 'No Info'
stardew_full = merged_stardew.fillna('No Info')
stardew_full = stardew_full.rename(columns={'Unnamed: 2': 'Character Birthday'})

In [170]:
stardew_full

,name,growth_time,Character,Character Birthday,Gift Loves and Likes,Universal Likes
0,Amaranth,7.0,No Info,No Info,No Info,No Info
1,Ancient Fruit,28.0,No Info,No Info,No Info,No Info
2,Artichoke,8.0,No Info,No Info,No Info,No Info
3,Beet,6.0,No Info,No Info,No Info,No Info
4,Blue Jazz,7.0,No Info,No Info,No Info,No Info
...,...,...,...,...,...,...
29,No Info,No Info,Harvey,Winter 14,"Super Meal, Lobster Bisque, Truffle Oil, Wine,...","Universal Likes (except Cheese, Goat Cheese, I..."
30,No Info,No Info,Wizard,Winter 17,"Super Cucumber, Purple Mushroom, Solar Essence...","Universal Likes, All Minerals."
31,No Info,No Info,Evelyn,Winter 20,"Beet, Chocolate Cake, Diamond, Fairy Rose, Stu...","Universal Likes (except Quartz, Fried Eel, Spi..."
32,No Info,No Info,Leah,Winter 23,"Salad, Vegetable Medley, Poppyseed Muffin, Sti...","Universal Likes (except Pizza, Pink Cake, Cook..."
33,No Info,No Info,Clint,Winter 26,"Emerald, Aquamarine, Ruby, Amethyst, Topaz, Ja...","Universal Likes (except Quartz, All Flowers), ..."

For this dataset, I wanted to create a table that shows how long items take to grow and
add it to each villagers liked and loved list. I made this so the user can check
what to gift a villager and if growing specific items is worth it. This one
did not work the way I had hoped because there are not common areas to merge so the set
is not good visually. I also renammed 'Unnamed: 2' to 'Character Birthday'. Next set I am going to merge the webscrapping data with the stardew_char_likes table.

In [173]:
merge_stardew_df = pd.merge(stardew_names_df, stardew_char_likes, on='Character')
merge_stardew_df = merge_stardew_df.rename(columns={'Unnamed: 2': 'Character Birthday'})
merge_stardew_df

,Character,Character Birthday,Gift Loves and Likes,Universal Likes
0,Alex,Summer 13,"Complete Breakfast, Salmon Dinner, Rabbit's Fo...","Universal Likes (except Quartz), All Eggs (exc..."
1,Harvey,Winter 14,"Super Meal, Lobster Bisque, Truffle Oil, Wine,...","Universal Likes (except Cheese, Goat Cheese, I..."
2,Sam,Summer 17,"Pizza, Cactus Fruit, Maple Bar, Tigerseye, Rab...","Universal Likes (except All Vegetables, Quartz..."
3,Sebastian,Winter 10,"Frozen Tear, Pumpkin Soup, Sashimi, Void Egg, ...","Universal Likes (except All Flowers, Fried Egg..."
4,Shane,Spring 20,"Beer, Hot Pepper, Pepper Poppers, Pizza, Rabbi...","Universal Likes (except Quartz, Pickles), All ..."
5,Emily,Spring 27,"Survival Burger, Emerald, Aquamarine, Ruby, Am...","Universal Likes (except Rice Pudding, Ice Crea..."
6,Haley,Spring 14,"Pink Cake, Fruit Salad, Coconut, Sunflower, Ra...","Universal Likes (except All Vegetables, Quartz..."
7,Leah,Winter 23,"Salad, Vegetable Medley, Poppyseed Muffin, Sti...","Universal Likes (except Pizza, Pink Cake, Cook..."
8,Maru,Summer 10,"Cheese Cauliflower, Cauliflower, Pepper Popper...","Universal Likes (except Honey, Maple Syrup, Pi..."
9,Penny,Fall 2,"Poppyseed Muffin, Red Plate, Tom Kha Soup, Roo...","Universal Likes (except Quartz, Beer, Wine, Pa..."
10,Caroline,Winter 7,"Fish Taco, Summer Spangle, Rabbit's Foot, Pris...","Universal Likes (except Quartz, Mayonnaise, Du..."
11,Clint,Winter 26,"Emerald, Aquamarine, Ruby, Amethyst, Topaz, Ja...","Universal Likes (except Quartz, All Flowers), ..."
12,Demetrius,Summer 19,"Bean Hotpot, Ice Cream, Rice Pudding, Strawber...","Universal Likes (except Quartz), All Eggs (exc..."
13,Dwarf,Summer 22,"Amethyst, Aquamarine, Emerald, Jade, Omni Geod...","Universal Likes, Dwarf Scroll I, Dwarf Scroll ..."
14,Evelyn,Winter 20,"Beet, Chocolate Cake, Diamond, Fairy Rose, Stu...","Universal Likes (except Quartz, Fried Eel, Spi..."
15,George,Fall 24,"Fried Mushroom, Leek, Rabbit's Foot, Prismatic...","Universal Likes (except Quartz, All Flowers), ..."
16,Gus,Summer 8,"Diamond, Escargot, Fish Taco, Orange, Rabbit's...","Universal Likes (except Quartz, Coleslaw), Daf..."
17,Jas,Summer 4,"Fairy Rose, Pink Cake, Plum Pudding, Rabbit's ...","Universal Likes (except All Vegetables, All Ar..."
18,Jodi,Fall 11,"Chocolate Cake, Crispy Bass, Diamond, Vegetabl...","Universal Likes (except Quartz, Garlic), All E..."
19,Kent,Spring 4,"Fiddlehead Risotto, Roasted Hazelnuts, Rabbit'...","Universal Like (except Quartz, Sashimi, Tortil..."
20,Krobus,Winter 1,"Diamond, Iridium Bar, Pumpkin, Void Egg, Wild ...","Universal Likes (except All Cooking), Gold Bar."
21,Lewis,Spring 7,"Vegetable Medley, Autumn's Bounty, Glazed Yams...","Universal Like (except Quartz), Parsnip, Cocon..."
22,Linus,Winter 3,"Blueberry Tart, Cactus Fruit, Coconut, Dish O'...","Universal Likes (except All Gems), All Eggs (e..."
23,Marnie,Fall 18,"Diamond, Farmer's Lunch, Pink Cake, Pumpkin Pi...","Universal Likes, All Eggs (except Void egg), A..."
24,Pam,Spring 18,"Parsnip Soup, Beer, Glazed Yams, Pale Ale Par...","Universal Likes (except Quartz), All Milk, All..."
25,Pierre,Spring 26,"Fried Calamari, Rabbit's Foot, Prismatic Shard.","Universal Likes (except All Gems, Tortilla, Pa..."
26,Robin,Fall 21,"Goat Cheese, Peach, Spaghetti, Rabbit's Foot, ...","Universal Likes, All Milk, All Fruits, Cheese,..."
27,Sandy,Fall 15,"Crocus, Daffodil, Sweet Pea, Rabbit's Foot, Pr...","Universal Likes, All Fruits, All Vegetables, C..."
28,Vincent,Spring 10,"Cranberry Candy, Pink Cake, Grape, Rabbit's Fo...","Universal Likes (except All Vegetables, All Ar..."
29,Willy,Summer 24,"Catfish, Diamond, Iridium Bar, Octopus, Pumpki...","Universal Likes (except All Cooking), Tiger Tr..."
30,Wizard,Winter 17,"Super Cucumber, Purple Mushroom, Solar Essence...","Universal Likes, All Minerals."

For this dataset I used the .merge function to merge the villagers from the webscrapping data with the liked and loved items list.
I renamed 'Unnamed: 2' to 'Character Birthday' since renaming it earlier in the program
was not changing the name.